services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
